name: 'Twister Results Analysis'
description: 'Analyse twister output file'
inputs:
  twister-result-file:
    description: 'path to twister.json produced by twister run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Analyse twister output file'
      shell: bash
      run: ${{ github.action_path }}/analyse_twister_results.py --file-report $GITHUB_STEP_SUMMARY --fail ${{ inputs.twister-result-file }}


