name: 'MCUboot for STM32 H7 banks'
description: |
  'Create hex files for each of STM32H7 banks where MCUboot is located.'
  'It also creates a single hex files containing MCUboot in each bank.'

inputs:
  mcuboot-binfile:
    description: 'Path to mcuboot binary which is usually loaded at 0x08000000'
    required: true

  board-name:
    description: 'Name of the board MCUboot was compiled for. It has no functionnal purposes other than producing meaningfull filenames.'
    required: true

  bank1-offset:
    description: 'Offset of the first bank'
    default: "0x08000000"

  bank2-offset:
    description: 'Offset of the second bank'
    default: "0x08100000"


outputs:
  mcuboot-banks-hexfile:
    description: 'Hex files containing MCUboot for both banks.'
    value: ${{ steps.filenames.outputs.banks_hex_file }}

  mcuboot-binfile:
    description: 'Binary file containing MCUboot, this is the same file as the input but with a meaningfull name (eg: <board-name>_mcuboot.bin)'
    value: ${{ steps.filenames.outputs.bin_file }}

  md5sum-file:
    description: 'MD5SUM file containing the md5 sum of each output file.'
    value: ${{ steps.filenames.outputs.md5sum_file }}


runs:
  using: 'composite'
  steps:
    # Abort early if srec_cat is not available
    - shell: bash
      id: which-srec-cat
      run: which srec_cat

    - shell: bash
      id: filenames
      run: |
        banks_hex_file="${{ inputs.board-name }}_mcuboot_banks.hex"
        bin_file="${{ inputs.board-name }}_mcuboot.bin"
        echo "banks_hex_file=${banks_hex_file}" >> $GITHUB_OUTPUT
        echo "bin_file=${bin_file}" >> $GITHUB_OUTPUT
        echo "md5sum_file=MD5SUM" >> $GITHUB_OUTPUT

    # Binary file with MCUboot properly named
    - shell: bash
      run: cp ${{ inputs.mcuboot-binfile }} ${{ steps.filenames.outputs.bin_file }}

    # Hex file with MCUboot in both banks
    - shell: bash
      run: srec_cat ${{ steps.filenames.outputs.bin_file }} -binary -offset ${{ inputs.bank1-offset }} ${{ steps.filenames.outputs.bin_file }} -binary -offset ${{ inputs.bank2-offset }} -Output ${{ steps.filenames.outputs.banks_hex_file }} -Intel

    # MD5 sum
    - shell: bash
      run: md5sum ${{ steps.filenames.outputs.banks_hex_file }} ${{ steps.filenames.outputs.bin_file }} >> ${{ steps.filenames.outputs.md5sum_file }}

    # debug
    - shell: bash
      run: |
        ls -l

    # Summary report
    - shell: bash
      if: ${{ failure() }} || ${{ success() }}
      run: |
        echo "## MCUboot for STM32 H7 Banks on ${{ inputs.board-name }}" >> ${GITHUB_STEP_SUMMARY}
        echo "which srec cat output: ${{ steps.which-srec-cat.outcome }}"
        if [ ${{ steps.which-srec-cat.outcome }} == 'failure' ]; then
          echo ":boom: \`srec_cat\` not available" >> ${GITHUB_STEP_SUMMARY}
        else
          echo "### Files produced" >> ${GITHUB_STEP_SUMMARY}
          echo "- \`${{ steps.filenames.outputs.banks_hex_file }}\`: MCUboot located in both banks" >> ${GITHUB_STEP_SUMMARY}
          echo "- \`${{ steps.filenames.outputs.bin_file }}\`: MCUboot binary file" >> ${GITHUB_STEP_SUMMARY}
          echo "- \`${{ steps.filenames.outputs.md5sum_file }}\`: md5 sum of above files." >> ${GITHUB_STEP_SUMMARY}
          echo "" >> ${GITHUB_STEP_SUMMARY}

          echo "### MD5 sums" >> ${GITHUB_STEP_SUMMARY}
          echo "\`\`\`" >> ${GITHUB_STEP_SUMMARY}
          cat ${{ steps.filenames.outputs.md5sum_file }} >> ${GITHUB_STEP_SUMMARY}
          echo "\`\`\`" >> ${GITHUB_STEP_SUMMARY}
        fi
