name: 'Github Context'
description: 'Show Context for Github vars'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo "github.action: ${{ github.action }}"
        echo "github.action_path: ${{ github.action_path }}"
        echo "github.action_ref: ${{ github.action_ref }}"
        echo "github.action_repository: ${{ github.action_repository }}"
        echo "github.action_status: ${{ github.action_status }}"
        echo "github.actor: ${{ github.actor }}"
        echo "github.actor_id: ${{ github.actor_id }}"
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.event_name: ${{ github.event_name }}"
        echo "github.event_path: ${{ github.event_path }}"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "github.job_id: ${{ github.job_id }}"
        echo "github.ref: ${{ github.ref }}"
        echo "github.ref_name: ${{ github.ref_name }}"
        echo "github.ref_type: ${{ github.ref_type }}"
        echo "github.repository: ${{ github.repository }}"
        echo "github.repository_id: ${{ github.repository_id }}"
        echo "github.repository_owner: ${{ github.repository_owner }}"
        echo "github.repository_owner_id: ${{ github.repository_owner_id }}"
        echo "github.run_id: ${{ github.run_id }}"
        echo "github.run_number: ${{ github.run_number }}"
        echo "github.run_attempt: ${{ github.run_attempt }}"
        echo "github.sha: ${{ github.sha }}"
        echo "github.triggering_actor: ${{ github.triggering_actor }}"
        echo "github.workflow: ${{ github.workflow }}"
        echo "github.workflow_ref: ${{ github.workflow_ref }}"
        echo "github.workflow_sha: ${{ github.workflow_sha }}"
        echo "github.workspace: ${{ github.workspace }}"
