name: MCUboot compilation

on:
  workflow_call:
    inputs:
      board-root-dir:
        description: 'Path to custom boards directory passed to --board-root option'
        required: false
        type: string
      key-file:
        description: 'Path where content of secret signing key is stored'
        required: true
        type: string
      twister-outdir:
        description: 'Twister output directory'
        required: false
        type: string
        default: "twister-out"
      tests-names:
        description: 'Space separated list of test case name to build'
        required: true
        type: string
      fallback-key-file:
        description: 'Key to use as fallback if signing-key is not available (action run from fork)'
        required: false
        type: string

    secrets:
      signing-key:
        description: 'Content of PEM key for which public part is stored in MCUboot firmware'
        required: true

jobs:
  mcuboot_compil:
    uses: SiemaApplications/vossloh-gh-actions/.github/workflows/twister-signed-compilation.yml@main
    with:
      app-dir: bootloader/mcuboot/boot/zephyr/
      board-root-dir: ${{ inputs.board-root-dir }}
      key-file: ${{ inputs.key-file }}
      twister-outdir: ${{ inputs.twister-outdir }}
      tests-names: ${{ inputs.tests-names }}
      fallback-key-file: ${{ inputs.fallback-key-file }}
    secrets:
      signing-key: ${{ secrets.signing-key }}

  get_mcuboot_bins:
    needs: mcuboot_compil
    name: MCUboot Binary Matrix
    runs-on: ubuntu-latest
    outputs:
      binaries-matrix: ${{ steps.binaries-matrix.outputs.binaries_matrix }}

    steps:
      - name: Get MCUboot binaries
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.mcuboot_compil.outputs.binaries }}

      - name: Get Binaries
        id: binaries-matrix
        run: |
          binaries_matrix="$(find . -name 'zephyr.bin' | jq -R -s -c 'split("\n") | map(select(length > 0))')"
          echo "binaries_matrix=${binaries_matrix}" >> $GITHUB_OUTPUT
          echo "binaries_matrix=${binaries_matrix}"


  sreccat:
    runs-on: ubuntu-latest
    name: MCUboot files for stm32h7 banks
    needs: get_mcuboot_bins
    strategy:
      matrix:
        mcuboot: ${{ fromJson(needs.get_mcuboot_bins.outputs.binaires-matrix) }}
    steps:
      - name: Get MCUboot binaries
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.mcuboot_compil.outputs.binaries }}

      - name: Get Board Name
        id: board-name
        run: |
          board="$(echo ${{ matrix.mcuboot }} | cut -d '/' -f 2)"
          echo "board=${board}" >> $GITHUB_OUTPUT

      - name: MCUboot STM32 H7 banks
        uses: SiemaApplications/vossloh-gh-actions/mcuboot/stm32h7-banks@main
        with:
          mcuboot-binfile: ${{ matrix.mcuboot }}
          board-name: ${{ steps.board-name.outputs.board }}
